name: caixa_simbiose
description: Projeto para gerenciar o caixa da atlética Simbiose.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.1
  flutter_native_splash: ^2.2.18
  flutter_launcher_icons: ^0.12.0

flutter_native_splash:
  color: "#000000"
  image: "lib/assets/images/simbiose-icon.png"
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/logo-simbiose.png
    - lib/assets/images/mascote-simbiose.png
    - lib/assets/images/mascote-simbiose-letreiro.png
    - lib/assets/images/simbiose-icon.png